Repository SERG-Delft/evosql, pull requests merged in 2018-04, with the labels that each got.

#27 Database type typing
  ga/src/main/java/nl/tudelft/serg/evosql/db/SchemaExtractor.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBBoolean.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBDate.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBDateTime.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBDouble.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBInteger.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBString.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBTime.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBType.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/type/DBTypeSelector.java
  ga/src/main/java/nl/tudelft/serg/evosql/path/PathExtractor.java
  ga/src/main/java/nl/tudelft/serg/evosql/sql/TableSchema.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBBooleanTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBDateTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBDateTimeTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBDoubleTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBIntegerTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBStringTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBTimeTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/type/DBTypeSelectorTest.java
Labels: enhancement

#26 Properly escape strings
  brew/src/main/java/nl/tudelft/serg/evosql/brew/sql/InsertionBuilder.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/sql/QueryBuilder.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/DataGenerator.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/sql/CleaningBuilderTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/sql/DestructionBuilderTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/sql/InsertionBuilderTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/sql/QueryBuilderTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/sql/SelectionBuilderTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/sql/TableCreationBuilderTest.java
Labels: bug, sub: brew

#28 Remove upper case transformations from GA
  brew/src/test/java/nl/tudelft/serg/evosql/brew/db/EvoSQLRunnerTest.java
  ga/src/main/java/nl/tudelft/serg/evosql/fixture/FixtureRow.java
  ga/src/main/java/nl/tudelft/serg/evosql/metaheuristics/GAApproach.java
  ga/src/main/java/nl/tudelft/serg/evosql/sql/TableSchema.java
  ga/src/main/java/nl/tudelft/serg/evosql/sql/parser/SqlSecurerVisitor.java
  ga/src/main/java/nl/tudelft/serg/evosql/sql/parser/TablesNamesFinder.java
  ga/src/main/java/nl/tudelft/serg/evosql/sql/parser/UsedColumnExtractor.java
  ga/src/main/java/nl/tudelft/serg/evosql/sql/parser/UsedColumnExtractorVisitor.java
  ga/src/test/java/nl/tudelft/serg/evosql/fixture/FixtureTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/mock/TableSchemaMocks.java
  ga/src/test/java/nl/tudelft/serg/evosql/sql/parser/SqlSecurerTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/sql/parser/UsedColumnExtractorTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/AggregatesTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/BetweenTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/CountTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/DistinctTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/ExistsTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/GroupByTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/HavingTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/InTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/InnerJoinTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/LeftJoinTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/LikeTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/LimitTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/NullTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/RightJoinTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/SelectTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/StringsTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/SubqueryFromTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/SubquerySelectWhereTest.java
  ga/src/test/java/nl/tudelft/serg/evosql/test/WhereTest.java
Labels: bug, enhancement

#30 Writing coffee: adds output consumers and pipelines
  brew/build.gradle
  brew/src/main/java/nl/tudelft/serg/evosql/brew/Pipeline.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/consumer/FileConsumer.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/consumer/OutputConsumer.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/consumer/PrintConsumer.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/generator/Generator.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/generator/Output.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnitGenerator.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnitGeneratorSettings.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/PipelineTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/consumer/FileConsumerTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/consumer/PrintConsumerTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnit4TestGeneratorTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnit5TestGeneratorTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnitGeneratorSettingsTest.java
  brew/src/test/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnitGeneratorTest.java
  brew/src/test/resources/java/jUnitGenerator/JUnit4MediumTest.java
  brew/src/test/resources/java/jUnitGenerator/JUnit4SmallTest.java
  brew/src/test/resources/java/jUnitGenerator/JUnit5MediumTest.java
  brew/src/test/resources/java/jUnitGenerator/JUnit5SmallTest.java
  build.gradle
  ga/build.gradle
  instrumented-hsqldb/build.gradle
Labels: enhancement, sub: brew

#31 Add Coveralls to integration checks
  .travis.yml
  brew/build.gradle
  ga/build.gradle
Labels: enhancement

#32 Fix builder class constructor access level to public
  brew/src/main/java/nl/tudelft/serg/evosql/brew/Pipeline.java
  brew/src/main/java/nl/tudelft/serg/evosql/brew/generator/junit/JUnitGeneratorSettings.java
Labels: bug, enhancement
